version: '3.9'

services:
  # PostgreSQL
  sentry-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - sentry-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis
  sentry-redis:
    image: redis:7
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - sentry-redis-data:/data
    restart: unless-stopped

  # ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:25.7
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    restart: unless-stopped

  # Snuba API
  snuba-api:
    image: getsentry/snuba:23.10.0
    depends_on:
      - clickhouse
    environment:
      CLICKHOUSE_HOST: clickhouse
      REDIS_HOST: sentry-redis
    command: api
    restart: unless-stopped

  # Snuba Consumer (optional)
  snuba-consumer:
    image: getsentry/snuba:23.10.0
    depends_on:
      - clickhouse
    environment:
      CLICKHOUSE_HOST: clickhouse
      REDIS_HOST: sentry-redis
    command: consumer
    restart: unless-stopped

  # Sentry Web
  sentry-web:
    image: getsentry/sentry:latest
    depends_on:
      - sentry-postgres
      - sentry-redis
      - snuba-api
    environment:
      SENTRY_SECRET_KEY: "58nis-*p(c9f-#2c)of#*6vfb=q(yecz88w_z0m-+"
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_DB_NAME: sentry
      SENTRY_DB_HOST: sentry-postgres
      SENTRY_REDIS_HOST: sentry-redis
      SENTRY_SNUBA_HOST: snuba-api
      SENTRY_CONF: /etc/sentry
    ports:
      - "9000:9000"
    volumes:
      - sentry-data:/data
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "mkdir -p /etc/sentry &&
       echo 'from sentry.conf.server import *' > /etc/sentry/sentry.conf.py &&
       echo 'system.secret-key: \"$SENTRY_SECRET_KEY\"' > /etc/sentry/config.yml &&
       sentry upgrade --noinput &&
       sentry createuser --email admin@example.com --superuser --password admin &&
       sentry run web"
    restart: unless-stopped

volumes:
  sentry-postgres-data:
  sentry-redis-data:
  clickhouse-data:
  sentry-data:
