version: "3.8"

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-db"]
    ports:
      - "13007:80"
      - "13008:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped

  web1:
    image: nginx:alpine
    container_name: web1

  web2:
    image: nginx:alpine
    container_name: web2
