version: "3.8"

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "13006:80"
      - "13007:8404" # painel de stats
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped
