version: "3.9"

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    ports:
      - "13006:13006"
      - "13007:13007"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    environment:
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Exemplo opcional de backends (remova se não quiser)
  web1:
    image: nginx:alpine
  web2:
    image: nginx:alpine
