version: '3.9'

services:
  # PostgreSQL
  sentry-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - sentry-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis
  sentry-redis:
    image: redis:7
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - sentry-redis-data:/data
    restart: unless-stopped

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

  # ClickHouse
  clickhouse:
    image: yandex/clickhouse-server:23.8
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    restart: unless-stopped

  # Snuba API
  snuba-api:
    image: getsentry/snuba:23.10.0
    depends_on:
      - clickhouse
      - kafka
      - zookeeper
    environment:
      CLICKHOUSE_HOST: clickhouse
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: sentry-redis
    command: api
    restart: unless-stopped

  # Snuba consumer (optional)
  snuba-consumer:
    image: getsentry/snuba:23.10.0
    depends_on:
      - clickhouse
      - kafka
      - zookeeper
    environment:
      CLICKHOUSE_HOST: clickhouse
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: sentry-redis
    command: consumer
    restart: unless-stopped

  # Sentry Web
  sentry-web:
    image: getsentry/sentry:latest
    depends_on:
      - sentry-postgres
      - sentry-redis
      - snuba-api
    environment:
      SENTRY_SECRET_KEY: "58nis-*p(c9f-#2c)of#*6vfb=q(yecz88w_z0m-+anc(^1d4^"
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_DB_NAME: sentry
      SENTRY_DB_HOST: sentry-postgres
      SENTRY_REDIS_HOST: sentry-redis
      SENTRY_SNUBA_HOST: snuba-api
    ports:
      - "9000:9000"
    volumes:
      - sentry-data:/data
    command: ["run", "web"]
    restart: unless-stopped

volumes:
  sentry-postgres-data:
  sentry-redis-data:
  clickhouse-data:
  sentry-data:
