version: "3.8"

services:
  sentry:
    image: sentry:21.6.0
    restart: unless-stopped
    environment:
      SENTRY_SECRET_KEY: "I6kLp3bT9mD7wZyQ0rVjGx8aP4eFuNsRtHb"
      SENTRY_TSDB: "sentry.tsdb.snuba.SnubaTSDB"
      SENTRY_EVENT_RETENTION_DAYS: 90
      SENTRY_SINGLE_ORGANIZATION: "true"
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
      - kafka
      - snuba
    volumes:
      - sentry-data:/var/lib/sentry

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  snuba:
    image: getsentry/snuba:21.6.0
    restart: unless-stopped
    depends_on:
      - clickhouse
      - kafka
      - redis
      - postgres
    environment:
      SNUBA_SETTINGS: docker
      CLICKHOUSE_HOST: clickhouse
      DEFAULT_BROKERS: kafka:9092
      REDIS_HOST: redis
      DATABASE_HOST: postgres

volumes:
  sentry-data:
  postgres-data:
  clickhouse-data:
