version: "3.9"

services:
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haproxy
    restart: unless-stopped
    ports:
      - "13006:80"
      - "13007:8404"  # painel de stats
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    environment:
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 30s
      timeout: 10s
      retries: 3
